//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.KHCF.Customization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST.KHCF.Customization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Accommodation&quot; FormType=&quot;ST_Accommodation&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Accommodation&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;418&quot; height=&quot;249&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_ACCOMMODATION&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Accommodation {
            get {
                return ResourceManager.GetString("Frm_Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Actual_Donations&quot; FormType=&quot;ST_Actual_Donations&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Actual Donations&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;1015&quot; height=&quot;450&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_ACTUAL_DONATIONS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Actual_Donations {
            get {
                return ResourceManager.GetString("Frm_Actual_Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Ambassador&quot; FormType=&quot;ST_Ambassador&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Ambassador Activity&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;768&quot; height=&quot;244&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_AMBASSADOR&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Ambassador {
            get {
                return ResourceManager.GetString("Frm_Ambassador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Areas_and_Transportation_Types&quot; FormType=&quot;ST_Areas_and_Transportation_Types&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Areas and Transportation Types&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;739&quot; height=&quot;219&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_AREAS_TRANS_TYPS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Areas_and_transportation_type {
            get {
                return ResourceManager.GetString("Frm_Areas_and_transportation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Booth_Commission&quot; FormType=&quot;ST_Booth_Commission&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Booth Commission &quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;473&quot; height=&quot;225&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_BOOTH_COMMISSION&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Booth_Commission {
            get {
                return ResourceManager.GetString("Frm_Booth_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Cards_Actions_From_File&quot; FormType=&quot;ST_Cards_Actions_From_File&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Cards Actions From File&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;911&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Cards_Actions_From_File {
            get {
                return ResourceManager.GetString("Frm_Cards_Actions_From_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Cards_List&quot; FormType=&quot;ST_Cards_List&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Cards Workflow&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;911&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RESULT&quot;&gt;
        ///              &lt;Col [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Cards_List {
            get {
                return ResourceManager.GetString("Frm_Cards_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Corporate_Membership&quot; FormType=&quot;ST_Corporate_Membership&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Corporate Membership&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;504&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_CORP_MEMBERSHIP&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_CCI_Corporate_Membership {
            get {
                return ResourceManager.GetString("Frm_CCI_Corporate_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Individual_Membership&quot; FormType=&quot;ST_Individual_Membership&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Individual Membership&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_INDIV_MEMBERSHIP&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_CCI_Individual_Membership {
            get {
                return ResourceManager.GetString("Frm_CCI_Individual_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_CCI_Member_Card&quot; FormType=&quot;ST_CCI_Member_Card&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Individual Member Card&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_CCI_INDIV_CARD&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_CCI_Member_Card {
            get {
                return ResourceManager.GetString("Frm_CCI_Member_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Revenue_Realization&quot; FormType=&quot;ST_Revenue_Realization&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Revenue Realization&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;936&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RESUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_CCI_Revenue_Realization {
            get {
                return ResourceManager.GetString("Frm_CCI_Revenue_Realization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Commission_Rules&quot; FormType=&quot;ST_Commission_Rules&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Commission Rules&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;407&quot; client_width=&quot;492&quot; client_height=&quot;299&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_COMMISSION_RULES&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Commission_Rules {
            get {
                return ResourceManager.GetString("Frm_Commission_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Communication_Log&quot; FormType=&quot;ST_Communication_Log&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Communication Log&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;672&quot; height=&quot;353&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_COMMUNICAT_LOG&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdataso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Communication_Log {
            get {
                return ResourceManager.GetString("Frm_Communication_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_CCI_Corporate_Member_Card&quot; FormType=&quot;ST_CCI_Corporate_Member_Card&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Corporate Member Card	&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;1003&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_CCI_CORP_CARD&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Corporate__Member_Card {
            get {
                return ResourceManager.GetString("Frm_Corporate__Member_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Coverage_Request&quot; FormType=&quot;ST_Coverage_Request&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Coverage Request&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;769&quot; height=&quot;413&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_COVERAGE_REQUEST&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Coverage_Request {
            get {
                return ResourceManager.GetString("Frm_Coverage_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Coverage_Rules&quot; FormType=&quot;ST_Coverage_Rules&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Coverage Rules&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;407&quot; client_width=&quot;492&quot; client_height=&quot;299&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_COVERAGE_RULES&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Coverage_Rules {
            get {
                return ResourceManager.GetString("Frm_Coverage_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Coverage_Transaction&quot; FormType=&quot;ST_Coverage_Transaction&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Coverage Transaction &quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;517&quot; top=&quot;121&quot; width=&quot;701&quot; height=&quot;381&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_COVERAGE_TRANS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Coverage_Transaction {
            get {
                return ResourceManager.GetString("Frm_Coverage_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Dreams_Come_True&quot; FormType=&quot;ST_Dreams_Come_True&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Dreams Come True&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;672&quot; height=&quot;428&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_DREAMS_COME_TRUE&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Dreams_Come_True {
            get {
                return ResourceManager.GetString("Frm_Dreams_Come_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Expected_Donations&quot; FormType=&quot;ST_Expected_Donations&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Expected Donations&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;1015&quot; height=&quot;450&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_EXPEC_DONATION&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Expected_Donations {
            get {
                return ResourceManager.GetString("Frm_Expected_Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Fund_Rules&quot; FormType=&quot;ST_Fund_Rules&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Fund Rules&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;517&quot; top=&quot;121&quot; width=&quot;1031&quot; height=&quot;394&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_FUND_RULES&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;ST_SUB_NATIONALITY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Fund_Rules {
            get {
                return ResourceManager.GetString("Frm_Fund_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Fund_Target&quot; FormType=&quot;ST_Fund_Target&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Allocation&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;517&quot; top=&quot;121&quot; width=&quot;662&quot; height=&quot;358&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_FUND_TARGET&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;Patients_Dets&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Fund_Target {
            get {
                return ResourceManager.GetString("Frm_Fund_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Fundraising_Corporate_Card&quot; FormType=&quot;ST_Fundraising_Corporate_Card&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Corporate Contact Card&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;1003&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_FUND_CORP_CARD&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Fundraising_Corporate_Card {
            get {
                return ResourceManager.GetString("Frm_Fundraising_Corporate_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Fundraising_Individual_Card&quot; FormType=&quot;ST_Fundraising_Individual_Card&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Individual Contact Card&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_FUND_INDIV_CARD&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Fundraising_Individual_Card {
            get {
                return ResourceManager.GetString("Frm_Fundraising_Individual_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Goodwill_Funds&quot; FormType=&quot;ST_Goodwill_Funds&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Goodwill Funds&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;517&quot; top=&quot;121&quot; width=&quot;791&quot; height=&quot;383&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_GOOD_WILL_FUNDS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Goodwill_Funds {
            get {
                return ResourceManager.GetString("Frm_Goodwill_Funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Grants&quot; FormType=&quot;ST_Grants&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Grants&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;640&quot; height=&quot;343&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_GRANTS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Grants {
            get {
                return ResourceManager.GetString("Frm_Grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Import_Data&quot; FormType=&quot;ST_Import_Data&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Import Data&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;911&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RESULT&quot;&gt;
        ///              &lt;Colu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Import_Data {
            get {
                return ResourceManager.GetString("Frm_Import_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Machinery&quot; FormType=&quot;ST_Machinery&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Machines&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;39&quot; width=&quot;658&quot; height=&quot;495&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_MACHINERY&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Machinery {
            get {
                return ResourceManager.GetString("Frm_Machinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Machinery_Installation_Det&quot; FormType=&quot;ST_Machinery_Installation_Det&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Machine Detials&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;39&quot; width=&quot;662&quot; height=&quot;473&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_MACHIN_DET&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Machinery_Installation_Det {
            get {
                return ResourceManager.GetString("Frm_Machinery_Installation_Det", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Membership_Renewal&quot; FormType=&quot;ST_Membership_Renewal&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Membership Renewal&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;911&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RESULT&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Membership_Renewal {
            get {
                return ResourceManager.GetString("Frm_Membership_Renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Memberships_Need_To_Active&quot; FormType=&quot;ST_Memberships_Need_To_Active&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Pre-Payment to AR Invoice&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;911&quot; height=&quot;406&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Memberships_Need_To_Active {
            get {
                return ResourceManager.GetString("Frm_Memberships_Need_To_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Monthly_Giving&quot; FormType=&quot;ST_Monthly_Giving&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Recurring Donation&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;517&quot; top=&quot;121&quot; width=&quot;699&quot; height=&quot;181&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_MONTHLY_GIVING&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Monthly_Giving {
            get {
                return ResourceManager.GetString("Frm_Monthly_Giving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Naming&quot; FormType=&quot;ST_Naming&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Areas&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;672&quot; height=&quot;381&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_NAMING&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Naming {
            get {
                return ResourceManager.GetString("Frm_Naming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Patient_Activity&quot; FormType=&quot;ST_Patient_Activity&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Patient Activities&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;739&quot; height=&quot;375&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_PATIENT_ACTIVITY&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Patient_Activity {
            get {
                return ResourceManager.GetString("Frm_Patient_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Patients_Card&quot; FormType=&quot;ST_Patients_Card&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Patients Card&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_PATIENTS_CARD&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_Cov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Patients_Card {
            get {
                return ResourceManager.GetString("Frm_Patients_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Plaque_Wall&quot; FormType=&quot;ST_Plaque_Wall&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Plaque Wall&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;672&quot; height=&quot;353&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_PLAQUE_WALL&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Plaque_Wall {
            get {
                return ResourceManager.GetString("Frm_Plaque_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Pledges&quot; FormType=&quot;ST_Pledges&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Pledges&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;769&quot; height=&quot;413&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_PLEDGES&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;Participants_Details&quot;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Pledges {
            get {
                return ResourceManager.GetString("Frm_Pledges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Potential_Grants&quot; FormType=&quot;ST_Potential_Grants&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Potential Grants &quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;732&quot; height=&quot;400&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_POTENTIAL_GRANTS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Potential_Grants {
            get {
                return ResourceManager.GetString("Frm_Potential_Grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Recommending_Recognitions&quot; FormType=&quot;ST_Recommending_Recognitions&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Recognition Criteria&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;600&quot; height=&quot;389&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_RECOMMEND_REC&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Recommending_Recognitions {
            get {
                return ResourceManager.GetString("Frm_Recommending_Recognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Sales_Target&quot; FormType=&quot;ST_Sales_Target&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Sales Target&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;600&quot; height=&quot;407&quot; client_width=&quot;492&quot; client_height=&quot;299&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_SALES_TARGET&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Sales_Target {
            get {
                return ResourceManager.GetString("Frm_Sales_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Schools_Universites&quot; FormType=&quot;ST_Schools_Universites&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Schools &amp;amp; Universities Activity&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;739&quot; height=&quot;375&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_SCHOOL_UNI&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Schools_Universites {
            get {
                return ResourceManager.GetString("Frm_Schools_Universites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Installment&quot; FormType=&quot;ST_Installment&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Set Installments&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;355&quot; height=&quot;368&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_INSTALLMENT&quot;&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Set_Installment {
            get {
                return ResourceManager.GetString("Frm_Set_Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Set_Stop_Card_Data&quot; FormType=&quot;ST_Set_Stop_Card_Data&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Set Stop Card Data&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;554&quot; height=&quot;199&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Set_Stop_Card_Data {
            get {
                return ResourceManager.GetString("Frm_Set_Stop_Card_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Social_Study&quot; FormType=&quot;ST_Social_Study&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Social Study&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;995&quot; height=&quot;510&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_SOCIAL_STUDY&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_ST_SOCIAL_STUDY {
            get {
                return ResourceManager.GetString("Frm_ST_SOCIAL_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Stop_Cancel_Children&quot; FormType=&quot;ST_Stop_Cancel_Children&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Membership`s Children&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;994&quot; height=&quot;430&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;Children&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Stop_Cancel_Children {
            get {
                return ResourceManager.GetString("Frm_Stop_Cancel_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Stop_Cancel_Children&quot; FormType=&quot;ST_Stop_Cancel_Children&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Membership`s Children&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;994&quot; height=&quot;430&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;Children&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Stop_Cancel_Children1 {
            get {
                return ResourceManager.GetString("Frm_Stop_Cancel_Children1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Stop_Cancel_Children&quot; FormType=&quot;ST_Stop_Cancel_Children&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Membership`s Children&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;0&quot; top=&quot;0&quot; width=&quot;994&quot; height=&quot;430&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;Children&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Stop_Cancel_Children2 {
            get {
                return ResourceManager.GetString("Frm_Stop_Cancel_Children2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;&quot; SupportedModes=&quot;15&quot; left=&quot;243&quot; top=&quot;9&quot; width=&quot;889&quot; height=&quot;559&quot; client_width=&quot;873&quot; client_height=&quot;520&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/userdatasources&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_System_Time_Sheet {
            get {
                return ResourceManager.GetString("Frm_System_Time_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Tracking_Recognitions&quot; FormType=&quot;ST_Tracking_Recognitions&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Recognitions&quot; visible=&quot;0&quot; default_button=&quot;1&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;451&quot; top=&quot;121&quot; width=&quot;655&quot; height=&quot;365&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_TRACKING_REC&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Tracing_Recognitions {
            get {
                return ResourceManager.GetString("Frm_Tracing_Recognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Treatment_Plan_Details&quot; FormType=&quot;ST_Treatment_Plan_Details&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Treatment Plan Details&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;769&quot; height=&quot;249&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_TREATM_PLAN_DET&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Treatment_Plan_Details {
            get {
                return ResourceManager.GetString("Frm_Treatment_Plan_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Waiting_List&quot; FormType=&quot;ST_Waiting_List&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Waiting List&quot; visible=&quot;0&quot; default_button=&quot;12&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;719&quot; height=&quot;440&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;RESULT&quot;&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Waiting_List {
            get {
                return ResourceManager.GetString("Frm_Waiting_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;ST_Won_Grants&quot; FormType=&quot;ST_Won_Grants&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Won Grants &quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;9&quot; color=&quot;0&quot; left=&quot;431&quot; top=&quot;121&quot; width=&quot;941&quot; height=&quot;497&quot; client_width=&quot;492&quot; client_height=&quot;298&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;ST_WON_GRANTS&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;OUDP&quot;&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Frm_Won_Grants {
            get {
                return ResourceManager.GetString("Frm_Won_Grants", resourceCulture);
            }
        }
    }
}
